# Setup
title:               CS50
tagline:             'Professional and Lifelong Learning'
description:         'With the rapid change in <a href="https://github.com/RahulSinghParmar" target="_blank">technology</a>, the demand for computer scientists is increasing. Find the right program for you and make a change. <br> Made by <a href="https://www.linkedin.com/in/rahul-singh-2b27211a7/" target="_blank">@rsp</a>.'
url:                 https://rahulsinghparmar.github.io/
baseurl:             '/CS50'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Rahul Singh Parmar
  url:               https://github.com/RahulSinghParmar
  email:             rahulsinghparmar4@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Custom vars
version:             0.1.7
google_analytics_id: #UA-XXXX-Y
